# Generated by Django 5.0 on 2023-12-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whychooseus',
            old_name='brand_descp',
            new_name='chooseus_descp',
        ),
        migrations.RenameField(
            model_name='whychooseus',
            old_name='brand_heading',
            new_name='chooseus_heading',
        ),
    ]
