# Generated by Django 5.0 on 2023-12-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContantUs',
            new_name='ContactUs',
        ),
    ]
