# Generated by Django 5.0 on 2023-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_brand_descp_whychooseus_chooseus_descp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_heading',
            field=models.CharField(max_length=200),
        ),
    ]
