# Generated by Django 5.0 on 2023-12-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='profileimg',
            field=models.ImageField(null=True, upload_to='media/core'),
        ),
    ]
