# Generated by Django 5.0 on 2023-12-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
