# Generated by Django 5.0 on 2023-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pricing_link_pricing_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='details',
            field=models.ManyToManyField(related_name='package_detail', to='core.pricing_detail'),
        ),
    ]
