# Generated by Django 5.0 on 2024-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pricing_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpmail', models.EmailField(max_length=254)),
                ('otp_value', models.CharField(max_length=50)),
            ],
        ),
    ]
