# Generated by Django 5.0 on 2024-01-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
