# Generated by Django 5.0 on 2024-01-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_otp_otp_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='user_otp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
