# Generated by Django 5.0 on 2024-01-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_otp_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='new_password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
