# Generated by Django 5.0 on 2024-01-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_otp_new_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='reenter_new_password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
