# Generated by Django 5.0 on 2024-01-05 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_otp_reenter_new_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='timing',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('purchase_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricing')),
                ('purchase_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
