# Generated by Django 5.0 on 2024-01-05 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pricing_timing_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
